import { GoogleGenAI, Modality } from "@google/genai";
import type { GenerateContentResponse } from "@google/genai";
import type { StickerStyle } from "../types";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const fileToBase64 = (file: File): Promise<string> =>
  new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve((reader.result as string).split(',')[1]);
    reader.onerror = (error) => reject(error);
  });


export const generateStickerFromImage = async (base64ImageData: string, mimeType: string, style: StickerStyle): Promise<string> => {
    try {
        const stickerifyPrompt = 'Convert this image into a vinyl sticker. It should have a thick, clean, solid white border around the subject. Keep the original image content as is, just add the sticker border. The background outside the white border should be transparent.';
        
        const redrawPrompt = `Task: Radically reimagine the user's image and create a vibrant, cartoon-style vinyl sticker. This is not just a filter; create a completely new, lively character.

Instructions:

1.  **Reimagine and Redraw:**
    *   **Core Task:** Do not just trace or apply a simple style. Fundamentally redraw the main subject as an energetic, expressive cartoon character.
    *   **Personality:** Give the character a distinct personality. If it's an animal, make it mischievous, heroic, or goofy. If it's a person, amplify their expression.
    *   **Dynamics & Pose:** Create a sense of life and motion. Put the character in a dynamic pose, as if they were captured mid-action.
    *   **Features:** Use classic animation principles. Exaggerate key features—big expressive eyes, dynamic lines of action, and simplified, powerful shapes.
    *   **Color:** Use a palette of vibrant, saturated, and glowing colors that pop. Use bold shading to give the character depth and volume.

2.  **Create Sticker Border:**
    *   Once the new cartoon character is complete, add a thick, clean, and solid white die-cut border around its entire silhouette.

3.  **Final Output:**
    *   The final image must be the completely new cartoon character with its white border, rendered on a fully transparent background.`;

        const prompt = style === 'stickerify' ? stickerifyPrompt : redrawPrompt;

        const response: GenerateContentResponse = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: {
              parts: [
                {
                  inlineData: {
                    data: base64ImageData,
                    mimeType: mimeType,
                  },
                },
                {
                  text: prompt,
                },
              ],
            },
            config: {
                responseModalities: [Modality.IMAGE],
            },
          });
          
          for (const part of response.candidates[0].content.parts) {
            if (part.inlineData) {
              const base64ImageBytes: string = part.inlineData.data;
              return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
            }
          }

        throw new Error("No image was generated by the API.");
    } catch(error) {
        console.error("Error generating sticker with Gemini:", error);
        throw new Error("API call failed to generate sticker.");
    }
}