
import { GoogleGenAI, Modality } from "@google/genai";
import type { GenerateContentResponse } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const fileToBase64 = (file: File): Promise<string> =>
  new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve((reader.result as string).split(',')[1]);
    reader.onerror = (error) => reject(error);
  });


export const generateStickerFromImage = async (base64ImageData: string, mimeType: string): Promise<string> => {
    try {
        const response: GenerateContentResponse = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: {
              parts: [
                {
                  inlineData: {
                    data: base64ImageData,
                    mimeType: mimeType,
                  },
                },
                {
                  text: 'Convert this image into a vinyl sticker. It should have a thick, clean, solid white border around the subject. Redraw it in a vibrant, clean, simplified cartoon or illustration style, enhancing the colors and details to look like a high-quality sticker. The background outside the white border should be transparent.',
                },
              ],
            },
            config: {
                responseModalities: [Modality.IMAGE],
            },
          });
          
          for (const part of response.candidates[0].content.parts) {
            if (part.inlineData) {
              const base64ImageBytes: string = part.inlineData.data;
              return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
            }
          }

        throw new Error("No image was generated by the API.");
    } catch(error) {
        console.error("Error generating sticker with Gemini:", error);
        throw new Error("API call failed to generate sticker.");
    }
}
